# ==== pytest ====
[tool.pytest.ini_options]
addopts = "-v --tb=short"
norecursedirs = [
    ".tox",
    ".git",
    "*/migrations/*",
    "*/static/*",
    "docs",
    "venv",
    "*/{{cookiecutter.project_slug}}/*",
]


# ==== black ====
[tool.black]
line-length = 120
target-version = ['py39']


# ==== isort ====
[tool.isort]
profile = "black"
line_length = 120
known_first_party = [
    "tests",
    "scripts",
    "hooks",
]


# ==== flake8 ====
[tool.flake8]
max-line-length = 120
exclude = [".tox",".git","*/migrations/*","*/static/CACHE/*","docs","node_modules","venv",".venv"]
